CPPs =  EX5.cpp Animal.cpp Buffalo.cpp Coral.cpp Cow.cpp Equidae.cpp Farm.cpp GreatWhiteShark.cpp Horse.cpp Lion.cpp Menu.cpp MobileAnimal.cpp PredatorAnimal.cpp Sheep.cpp Sponge.cpp StaticAnimal.cpp VeganAnimal.cpp Wolf.cpp Zebra.cpp Zoo.cpp
target = ex5
all: $(CPPs)
	g++ ${CPPs} -std=c++0x -o ${target}

clean:
	rm *.o


